export const RULES = {
  secrets: [
    { id: 'S-AWS-001', name: 'AWS Access Key', pattern: /AKIA[0-9A-Z]{16}/g, severity: 'CRÍTICO' },
    { id: 'S-AWS-SEC-001', name: 'AWS Secret Key', pattern: /aws(_secret)?_access_key\s*[=:]\s*["'][A-Za-z0-9\/+=]{40}["']/gi, severity: 'CRÍTICO' },
    { id: 'S-GH-001', name: 'GitHub Personal Token', pattern: /ghp_[0-9a-zA-Z]{36}/g, severity: 'CRÍTICO' },
    { id: 'S-GH-ORG-001', name: 'GitHub Organization Token', pattern: /gho_[0-9a-zA-Z]{36}/g, severity: 'CRÍTICO' },
    { id: 'S-GH-APP-001', name: 'GitHub App Token', pattern: /ghu_[0-9a-zA-Z]{36}/g, severity: 'CRÍTICO' },
    { id: 'S-NPM-001', name: 'NPM Token', pattern: /npm_[A-Za-z0-9]{36}/g, severity: 'CRÍTICO' },
    { id: 'S-SK-STRIPE-001', name: 'Stripe Live Secret', pattern: /sk_live_[0-9a-zA-Z]{24}/g, severity: 'CRÍTICO' },
    { id: 'S-SK-STRIPE-TEST-001', name: 'Stripe Test Secret', pattern: /sk_test_[0-9a-zA-Z]{24}/g, severity: 'ALTO' },
    { id: 'S-FB-001', name: 'Firebase API Key', pattern: /AIza[0-9A-Za-z\-_]{35}/g, severity: 'ALTO' },
    { id: 'S-GCLOUD-001', name: 'Google Cloud API Key', pattern: /AIza[0-9A-Za-z\-_]{35}/g, severity: 'ALTO' },
    { id: 'S-SENDGRID-001', name: 'SendGrid API Key', pattern: /SG\.[0-9A-Za-z\-_]{22}\.[0-9A-Za-z\-_]{43}/g, severity: 'CRÍTICO' },
    { id: 'S-MAILGUN-001', name: 'Mailgun API Key', pattern: /key-[0-9A-Za-z]{32}/g, severity: 'CRÍTICO' },
    { id: 'S-TWILIO-001', name: 'Twilio API Key', pattern: /SK[a-f0-9]{32}/g, severity: 'CRÍTICO' },
    { id: 'S-SLACK-001', name: 'Slack Token', pattern: /xox[baprs]-[0-9a-zA-Z-]+/g, severity: 'CRÍTICO' },
    { id: 'S-JWT-001', name: 'JWT Token', pattern: /eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}/g, severity: 'ALTO' },
    { id: 'S-PK-PEM-001', name: 'Private Key PEM', pattern: /-----BEGIN (?:RSA |EC |DSA |OPENSSH |ENCRYPTED )?PRIVATE KEY-----/g, severity: 'CRÍTICO' },
    { id: 'S-CERT-001', name: 'Certificate PEM', pattern: /-----BEGIN CERTIFICATE-----/g, severity: 'ALTO' },
    { id: 'S-PSQL-001', name: 'PostgreSQL URL', pattern: /postgres(ql)?:\/\/[^\s"']+/gi, severity: 'CRÍTICO' },
    { id: 'S-MYSQL-001', name: 'MySQL URL', pattern: /mysql:\/\/[^\s"']+/gi, severity: 'CRÍTICO' },
    { id: 'S-MONGODB-001', name: 'MongoDB URL', pattern: /mongodb(\+srv)?:\/\/[^\s"']+/gi, severity: 'CRÍTICO' },
    { id: 'S-REDIS-001', name: 'Redis URL', pattern: /redis:\/\/[^\s"']+/gi, severity: 'CRÍTICO' },
    { id: 'S-RABBITMQ-001', name: 'RabbitMQ URL', pattern: /amqp:\/\/[^\s"']+/gi, severity: 'CRÍTICO' },
    { id: 'S-AZURE-001', name: 'Azure Connection String', pattern: /DefaultEndpointsProtocol=https?;AccountName=[^;]+;AccountKey=[^;]+/gi, severity: 'CRÍTICO' },
    { id: 'S-BASIC-AUTH-001', name: 'Basic Auth URL', pattern: /https?:\/\/[^\s"']+:[^\s"']+@[^\s"']+/gi, severity: 'CRÍTICO' },
  ],
  vulnerabilities: [
    { id: 'V-SQL-001', name: 'SQL Injection Risk', patterns: [
      /["']SELECT[^"']*\+.*|["']SELECT[^"']*\+=|\+.*["']SELECT/gi,
      /execute\s*\(\s*[`'"].*\+/g,
      /query\s*\(\s*[`'"].*\$/g,
      /"\s*\+\s*req\./g,
    ], severity: 'CRÍTICO', category: 'SQL_INJECTION' },
    { id: 'V-EVAL-001', name: 'Dangerous eval() Usage', patterns: [
      /\beval\s*\(\s*/g,
      /\bFunction\s*\(\s*/g,
    ], severity: 'CRÍTICO', category: 'CODE_INJECTION' },
    { id: 'V-CMD-001', name: 'Command Injection Risk', patterns: [
      /exec\s*\(\s*[^,]+\+/g,
      /execSync\s*\(\s*[^,]+\+/g,
      /spawn\s*\(\s*[^,]+\+/g,
      /execFile\s*\(\s*[^,]+\+/g,
    ], severity: 'CRÍTICO', category: 'CMD_INJECTION' },
    { id: 'V-XSS-001', name: 'XSS via innerHTML', patterns: [
      /\.innerHTML\s*=/g,
      /\.outerHTML\s*=/g,
      /document\.write\s*\(/g,
      /insertAdjacentHTML\s*\(/g,
    ], severity: 'ALTO', category: 'XSS' },
    { id: 'V-OPEN-REDIR-001', name: 'Open Redirect', patterns: [
      /window\.location\s*=\s*req\./g,
      /window\.location\.href\s*=\s*req\./g,
      /res\.redirect\s*\(\s*req\./g,
    ], severity: 'ALTO', category: 'OPEN_REDIRECT' },
    { id: 'V-PATH-TRAV-001', name: 'Path Traversal', patterns: [
      /readFile\s*\(\s*req\./g,
      /readFileSync\s*\(\s*req\./g,
      /createReadStream\s*\(\s*req\./g,
    ], severity: 'ALTO', category: 'PATH_TRAVERSAL' },
    { id: 'V-HARDCODED-PASS-001', name: 'Hardcoded Password', patterns: [
      /password\s*[=:]\s*["'][^"']{6,}["']/gi,
      /passwd\s*[=:]\s*["'][^"']{6,}["']/gi,
      /pwd\s*[=:]\s*["'][^"']{6,}["']/gi,
    ], severity: 'ALTO', category: 'HARDCODED_CREDENTIALS' },
    { id: 'V-DES-001', name: 'Insecure Cipher DES', patterns: [
      /createCipher\s*\(\s*['"]des['"]\s*\)/gi,
      /createDecipher\s*\(\s*['"]des['"]\s*\)/gi,
    ], severity: 'ALTO', category: 'WEAK_CRYPTO' },
    { id: 'V-RC4-001', name: 'Insecure Cipher RC4', patterns: [
      /createCipheriv\s*\(\s*['"]rc4['"]/gi,
    ], severity: 'ALTO', category: 'WEAK_CRYPTO' },
    { id: 'V-MATH-RANDOM-001', name: 'Insecure Random', patterns: [
      /Math\.random\s*\(\s*\)/g,
    ], severity: 'MEDIO', category: 'INSECURE_RANDOM' },
    { id: 'V-DISABLE-VERIFY-001', name: 'SSL Verification Disabled', patterns: [
      /rejectUnauthorized\s*:\s*false/g,
      /secure\s*:\s*false/g,
      /VERIFY_NONE/g,
    ], severity: 'ALTO', category: 'DISABLED_SSL_VERIFY' },
    { id: 'V-TRACE-001', name: 'HTTP TRACE Enabled', patterns: [
      /enable\s*:\s*['"]trace['"]/g,
    ], severity: 'MEDIO', category: 'HTTP_TRACE' },
    { id: 'V-DEBUG-001', name: 'Debug Mode Enabled', patterns: [
      /debug\s*:\s*true/g,
      /DEBUG\s*=\s*['"]true['"]/gi,
    ], severity: 'MEDIO', category: 'DEBUG_ENABLED' },
    { id: 'V-JWT-NONE-001', name: 'JWT Algorithm None', patterns: [
      /algorithm\s*:\s*['"]none['"]/gi,
    ], severity: 'CRÍTICO', category: 'JWT_ALGORITHM_CONFUSION' },
  ],
  files: [
    { name: '.env', label: 'Environment File', severity: 'CRÍTICO' },
    { name: '.env.local', label: 'Local Environment', severity: 'ALTO' },
    { name: '.env.production', label: 'Production Environment', severity: 'CRÍTICO' },
    { name: '.env.development', label: 'Development Environment', severity: 'ALTO' },
    { name: '.env.test', label: 'Test Environment', severity: 'ALTO' },
    { name: '.env.example', label: 'Environment Example', severity: 'MEDIO' },
    { name: 'serviceAccountKey.json', label: 'Firebase Service Account', severity: 'CRÍTICO' },
    { name: 'credentials.json', label: 'GCP Credentials', severity: 'CRÍTICO' },
    { name: 'credentials.db', label: 'Database Credentials File', severity: 'CRÍTICO' },
    { name: 'id_rsa', label: 'SSH Private Key', severity: 'CRÍTICO' },
    { name: 'id_dsa', label: 'SSH DSA Private Key', severity: 'CRÍTICO' },
    { name: 'id_ecdsa', label: 'SSH ECDSA Private Key', severity: 'CRÍTICO' },
    { name: '*.pem', label: 'PEM Certificate/Key', severity: 'CRÍTICO' },
    { name: '*.key', label: 'Private Key File', severity: 'CRÍTICO' },
    { name: '*.p12', label: 'PKCS12 Keystore', severity: 'CRÍTICO' },
    { name: '*.jks', label: 'Java Keystore', severity: 'CRÍTICO' },
    { name: 'dump.sql', label: 'SQL Dump', severity: 'CRÍTICO' },
    { name: 'database.sql', label: 'Database SQL', severity: 'CRÍTICO' },
    { name: 'htpasswd', label: 'htpasswd File', severity: 'CRÍTICO' },
    { name: '.htaccess', label: 'htaccess (may contain rules)', severity: 'MEDIO' },
    { name: '.git-credentials', label: 'Git Credentials', severity: 'CRÍTICO' },
    { name: 'secrets.yaml', label: 'Kubernetes Secrets', severity: 'CRÍTICO' },
    { name: 'secrets.yml', label: 'Kubernetes Secrets', severity: 'CRÍTICO' },
    { name: 'config.ini', label: 'Config File with Secrets', severity: 'ALTO' },
    { name: 'settings.py', label: 'Django Settings (may contain secrets)', severity: 'ALTO' },
    { name: 'local_settings.py', label: 'Django Local Settings', severity: 'ALTO' },
    { name: '*.log', label: 'Log File (may contain sensitive data)', severity: 'MEDIO' },
    { name: 'npm-debug.log', label: 'NPM Debug Log', severity: 'MEDIO' },
    { name: 'yarn-error.log', label: 'Yarn Error Log', severity: 'MEDIO' },
  ]
};

export const LANGUAGE_EXTENSIONS = {
  javascript: /\.(js|mjs|cjs)$/i,
  typescript: /\.(ts|mts|cts|tsx)$/i,
  python: /\.py$/i,
  php: /\.php$/i,
  java: /\.java$/i,
  csharp: /\.(cs|xaml)$/i,
  go: /\.go$/i,
  ruby: /\.rb$/i,
  rust: /\.rs$/i,
  kotlin: /\.kt$/i,
  swift: /\.swift$/i,
  yaml: /\.(yaml|yml)$/i,
  json: /\.json$/i,
  xml: /\.(xml|plist)$/i,
  config: /\.(config|conf)$/i,
  sql: /\.sql$/i,
  html: /\.(html|htm)$/i,
  css: /\.css$/i,
  shell: /\.(sh|bash|zsh)$/i,
  dockerfile: /Dockerfile$/i,
};

export const SKIP_DIRS = new Set([
  'node_modules', '.git', 'dist', 'build', '.next', '.nuxt',
  '__pycache__', 'venv', '.venv', 'env', '.env', 'vendor',
  'coverage', '.coverage', 'htmlcov', '.tox', 'target',
  '.gradle', 'bin', 'obj', '.idea', '.vscode', 'android',
  'ios', '.expo', '.cache', '.parcel-cache', '.turbo',
  'public', 'static', 'assets', '.svelte-kit', '.solid',
]);

export const MAX_FILE_SIZE = 1024 * 1024;